from openenv.core.env_server.types import Action, Observation
from pydantic import Field


class SqlQueryAction(Action):
    sql_query: str = Field(..., description="SQL query generated by AI")


class SqlQueryObservation(Observation):
    question: str
    schema: str
    difficulty: str
    reward: float
    done: bool
    feedback: str